# Generated by Django 5.0.6 on 2024-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
